language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "3.6"

script:
  - flake8

install:
  - pip install -U pip wheel
  - pip install -e ".[test]"

  - pip install -U flake8

sudo: false